vti_encoding:SR|utf8-nl
vti_cachedlinkinfo:VX|
vti_syncwith_tacjagr3\:80/sma_stage:TR|16 Aug 2000 12:01:03 -0600
vti_timecreated:TR|16 Aug 2000 12:01:03 -0600
vti_syncwith_m63648\:80/sma2:TR|16 Aug 2000 12:01:03 -0600
vti_cacheddtm:TX|16 Aug 2000 12:01:03 -0600
vti_sourcecontrolcookie:SX|C:\\Program Files\\Microsoft Visual Studio\\VSS\\srcsafe.ini
vti_syncwith_m63504\:80/sma2-dan:TR|16 Aug 2000 11:01:03 -0600
vti_timelastmodified:TR|16 Aug 2000 12:01:03 -0600
vti_cachedhasbots:BR|false
vti_sourcecontrolversion:SX|V1
vti_filesize:IX|16181
vti_syncwith_ism101394\:80/sma2dev:TR|16 Aug 2000 12:01:03 -0600
vti_extenderversion:SR|3.0.2.1105
vti_backlinkinfo:VX|
vti_syncwith_m69847\:80/sma2:TR|16 Aug 2000 11:01:03 -0600
vti_syncwith_mpr-098\:80/sma2:TR|16 Aug 2000 11:01:03 -0600
vti_cachedhasborder:BR|false
vti_author:SR|TAC_DOM1\\t098346
vti_cachedhastheme:BR|false
